[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "nodejs_22", "pnpm"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php -d upload_max_filesize=20M -d post_max_size=25M -d max_execution_time=120 -d max_input_time=120 artisan serve --host=0.0.0.0 --port=$PORT"
